language: cpp

matrix:
  include:
    - os: linux
      dist: focal
      compiler: gcc

before_install:
  - sudo apt-get -y install libgtest-dev

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - make test

notifications:
  email:
    recipients:
      - 9634619+day253@users.noreply.github.com
    on_success: never
    on_failure: always
